**2.Introduction to dataset.Dataset upoad.Numpy and panads library methods.Data Preprocessing**.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr=np.array([[1,2,3,4,5],[1,2,3,4,6]])
print(arr)

[[1 2 3 4 5]
 [1 2 3 4 6]]

In [ ]:

np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.random.randint(1,100,size=(2,2))

array([[86, 59],
       [99,  2]])

In [ ]:
np.random.rand(3,2)

array([[0.71925381, 0.90926633],
       [0.45792214, 0.53506193],
       [0.05666621, 0.55799448]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
print(arr.shape)

(2, 5)

In [ ]:
print(arr.ndim)

2

In [ ]:
print(arr.dtype)

int64

In [ ]:
df=pd.read_csv("stock2.csv")

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Adj Close
0,2016-07-01,17924.240234,18002.380859,17916.910156,17949.369141,82160000,17949.369141
1,2016-06-30,17712.759766,17930.609375,17711.800781,17929.990234,133030000,17929.990234
2,2016-06-29,17456.019531,17704.509766,17456.019531,17694.679688,106380000,17694.679688
3,2016-06-28,17190.509766,17409.720703,17190.509766,17409.720703,112190000,17409.720703
4,2016-06-27,17355.210938,17355.210938,17063.080078,17140.240234,138740000,17140.240234

In [ ]:
df.tail(3)

,Date,Open,High,Low,Close,Volume,Adj Close
1986,2008-08-12,11781.700195,11782.349609,11601.519531,11642.469727,173590000,11642.469727
1987,2008-08-11,11729.669922,11867.110352,11675.530273,11782.349609,183190000,11782.349609
1988,2008-08-08,11432.089844,11759.959961,11388.040039,11734.320312,212830000,11734.320312

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1989 non-null   object
 1   Open       1989 non-null   float64
 2   High       1989 non-null   float64
 3   Low        1989 non-null   float64
 4   Close      1989 non-null   float64
 5   Volume     1989 non-null   int64
 6   Adj Close  1989 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 108.9+ KB

In [ ]:
df.shape

(1989, 7)

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')

In [ ]:
print(df.isnull().sum())

Date         0
Open         0
High         0
Low          0
Close        0
Volume       0
Adj Close    0
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
print(df.dtypes)

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Volume                int64
Adj Close           float64
dtype: object

In [ ]:
print(df.describe())

                                Date          Open          High  \
count                           1989   1989.000000   1989.000000
mean   2012-07-20 11:52:23.891402752  13459.116048  13541.303173
min              2008-08-08 00:00:00   6547.009766   6709.609863
25%              2010-07-30 00:00:00  10907.339844  11000.980469
50%              2012-07-19 00:00:00  13022.049805  13088.110352
75%              2014-07-14 00:00:00  16477.699219  16550.070312
max              2016-07-01 00:00:00  18315.060547  18351.359375
std                              NaN   3143.281634   3136.271725

                Low         Close        Volume     Adj Close
count   1989.000000   1989.000000  1.989000e+03   1989.000000
mean   13372.931728  13463.032255  1.628110e+08  13463.032255
min     6469.950195   6547.049805  8.410000e+06   6547.049805
25%    10824.759766  10913.379883  1.000000e+08  10913.379883
50%    12953.129883  13025.580078  1.351700e+08  13025.580078
75%    16392.769531  16478.410156  1.926000e+08  16478.410156
max    18272.560547  18312.390625  6.749200e+08  18312.390625
std     3150.420934   3144.006996  9.392343e+07   3144.006996

In [ ]:
Q1 = df["Close"].quantile(0.25)
Q3 = df["Close"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df["Close"] < Q1 - 1.5 * IQR) |
              (df["Close"] > Q3 + 1.5 * IQR)]

print(outliers)

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume, Adj Close]
Index: []

In [ ]:
df.rename(columns={
    "Adj Close": "Adjusted_Close"
}, inplace=True)

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adjusted_Close'], dtype='object')

In [ ]:
df.drop("Adjusted_Close", axis=1)

,Date,Open,High,Low,Close,Volume
0,2016-07-01,17924.240234,18002.380859,17916.910156,17949.369141,82160000
1,2016-06-30,17712.759766,17930.609375,17711.800781,17929.990234,133030000
2,2016-06-29,17456.019531,17704.509766,17456.019531,17694.679688,106380000
3,2016-06-28,17190.509766,17409.720703,17190.509766,17409.720703,112190000
4,2016-06-27,17355.210938,17355.210938,17063.080078,17140.240234,138740000
...,...,...,...,...,...,...
1984,2008-08-14,11532.070312,11718.280273,11450.889648,11615.929688,159790000
1985,2008-08-13,11632.809570,11633.780273,11453.339844,11532.959961,182550000
1986,2008-08-12,11781.700195,11782.349609,11601.519531,11642.469727,173590000
1987,2008-08-11,11729.669922,11867.110352,11675.530273,11782.349609,183190000
1988,2008-08-08,11432.089844,11759.959961,11388.040039,11734.320312,212830000